# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "31699ca11bcaf8a0844acfca832c18a5"
name = "you-tm"
application_url = "https://reforms-threat-recently-mtv.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "youtm-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://reforms-threat-recently-mtv.trycloudflare.com/auth/callback",
  "https://reforms-threat-recently-mtv.trycloudflare.com/auth/shopify/callback",
  "https://reforms-threat-recently-mtv.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
